name: object_builder
description: Object builder generator for Dart
version: 0.1.0
repository: https://github.com/kerdokurs/object_builder

environment:
  sdk: '>=2.14.2 <3.0.0'

dependencies:
  path: ^1.8.0
  source_gen: ^1.2.2

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
  build_runner: ^2.1.10
